#!/bin/bash

echo "🧪 Test Manuel de l'Application Flutter"
echo "======================================"

echo "📱 Instructions pour tester manuellement :"
echo ""
echo "1. 🌐 Ouvrez Chrome et allez sur : http://localhost:8085"
echo ""
echo "2. 🎮 Testez le Mode Solo :"
echo "   - Cliquez sur 'MODE SOLO'"
echo "   - Cliquez sur 'START'"
echo "   - Vérifiez que le chrono de 3 secondes se lance"
echo "   - Vérifiez la redirection vers la Salle 1"
echo ""
echo "3. 👥 Testez le Mode Multijoueur :"
echo "   - Ouvrez un 2ème onglet avec la même URL"
echo "   - Dans l'onglet 1 : Cliquez sur 'MODE MULTIJOUEUR'"
echo "   - Créez une room avec un nom (ex: 'Test Room')"
echo "   - Dans l'onglet 2 : Cliquez sur 'MODE MULTIJOUEUR'"
echo "   - Rejoignez la room créée"
echo ""
echo "4. 🔍 Vérifiez la Détection des Joueurs :"
echo "   - Regardez le compteur 'Joueurs actifs: X/2'"
echo "   - Vérifiez que les 2 joueurs apparaissent avec 'Actif'"
echo "   - Vérifiez que le bouton 'ALLER À START' apparaît"
echo ""
echo "5. 🚀 Testez le Déclenchement Automatique :"
echo "   - Cliquez sur 'ALLER À START' dans un des onglets"
echo "   - Vérifiez que les 2 joueurs arrivent sur la page Start"
echo "   - Cliquez sur 'START' dans un des onglets"
echo "   - Vérifiez la synchronisation et le chrono"
echo ""
echo "6. 🎯 Testez la Salle 1 Multijoueur :"
echo "   - Vérifiez que les 2 joueurs arrivent dans la Salle 1"
echo "   - Vérifiez l'affichage des progrès de l'autre joueur"
echo "   - Testez la synchronisation des transitions"
echo ""
echo "7. 🚪 Testez la Gestion des Déconnexions :"
echo "   - Fermez un des onglets"
echo "   - Vérifiez que l'autre joueur est déconnecté automatiquement"
echo "   - Vérifiez le message 'La room est maintenant vide'"
echo ""
echo "📊 Points de Vérification :"
echo "✅ Page d'accueil : Choix Solo/Multijoueur direct"
echo "✅ Mode Solo : Chrono immédiat au clic START"
echo "✅ Mode Multijoueur : Détection des joueurs actifs"
echo "✅ Synchronisation : Page Start commune"
echo "✅ Salle 1 : Progrès partagés entre joueurs"
echo "✅ Déconnexions : Gestion automatique des salles vides"
echo ""
echo "🐛 Si vous rencontrez des problèmes :"
echo "   - Ouvrez la console du navigateur (F12)"
echo "   - Regardez les erreurs dans la console"
echo "   - Vérifiez que le serveur backend tourne sur localhost:5002"
echo ""
echo "🎉 Bon test !"
