// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUxg49zSnarmKRkuAQFG6dBhTiCcy2AMo',
    appId: '1:519180282303:web:57de096e5374398fc8190a',
    messagingSenderId: '519180282303',
    projectId: 'pandora-box-user2',
    authDomain: 'pandora-box-user2.firebaseapp.com',
    databaseURL: 'https://pandora-box-user2-default-rtdb.firebaseio.com',
    storageBucket: 'pandora-box-user2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxg49zSnarmKRkuAQFG6dBhTiCcy2AMo',
    appId: '1:519180282303:android:PLACEHOLDER', // À remplacer quand vous ajouterez l'app Android
    messagingSenderId: '519180282303',
    projectId: 'pandora-box-user2',
    databaseURL: 'https://pandora-box-user2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxg49zSnarmKRkuAQFG6dBhTiCcy2AMo',
    appId: '1:519180282303:ios:PLACEHOLDER', // À remplacer quand vous ajouterez l'app iOS
    messagingSenderId: '519180282303',
    projectId: 'pandora-box-user2',
    databaseURL: 'https://pandora-box-user2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxg49zSnarmKRkuAQFG6dBhTiCcy2AMo',
    appId: '1:519180282303:ios:PLACEHOLDER', // À remplacer quand vous ajouterez l'app macOS
    messagingSenderId: '519180282303',
    projectId: 'pandora-box-user2',
    databaseURL: 'https://pandora-box-user2-default-rtdb.firebaseio.com',
  );
}
