// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPN6G39XhgXKMK6C7DvuebG0pd_WeKz4',
    appId: '1:126460334259:web:db5a3c520c1f866ab060c6',
    messagingSenderId: '126460334259',
    projectId: 'pandora-d7a90',
    authDomain: 'pandora-d7a90.firebaseapp.com',
    databaseURL: 'https://pandora-d7a90-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pandora-d7a90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPN6G39XhgXKMK6C7DvuebG0pd_WeKz4', // Utilise la même clé API pour l'instant
    appId: '1:126460334259:android:PLACEHOLDER', // À remplacer quand vous ajouterez l'app Android
    messagingSenderId: '126460334259',
    projectId: 'pandora-d7a90',
    databaseURL: 'https://pandora-d7a90-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPN6G39XhgXKMK6C7DvuebG0pd_WeKz4', // Utilise la même clé API pour l'instant
    appId: '1:126460334259:ios:PLACEHOLDER', // À remplacer quand vous ajouterez l'app iOS
    messagingSenderId: '126460334259',
    projectId: 'pandora-d7a90',
    databaseURL: 'https://pandora-d7a90-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPN6G39XhgXKMK6C7DvuebG0pd_WeKz4', // Utilise la même clé API pour l'instant
    appId: '1:126460334259:ios:PLACEHOLDER', // À remplacer quand vous ajouterez l'app macOS
    messagingSenderId: '126460334259',
    projectId: 'pandora-d7a90',
    databaseURL: 'https://pandora-d7a90-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
