mutation CreateFoo($name: String!, $description: String) @auth(level: USER) {
  foo_insert(data: {
    name: $name,
    description: $description
  })
}

query ListFoos @auth(level: PUBLIC) {
  foos {
    id
    name
    description
  }
}

mutation UpdateFoo($id: UUID!, $name: String, $description: String) @auth(level: USER) {
  foo_update(key: {id: $id}, data: {
    name: $name,
    description: $description
  })
}

mutation DeleteFoo($id: UUID!) @auth(level: USER) {
  foo_delete(key: {id: $id})
}