type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  bio: String
  socialMediaLinks: [String]
}

type Stakeholder @table {
  name: String!
  type: String!
  createdAt: Timestamp!
  contactEmail: String
  contactPhone: String
  company: String
  notes: String
}

type Contract @table {
  user: User!
  stakeholder: Stakeholder!
  title: String!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
  description: String
  deliverables: String
  paymentTerms: String
  status: String
}

type Task @table {
  user: User!
  contract: Contract
  stakeholder: Stakeholder
  description: String!
  dueDate: Timestamp!
  status: String!
  createdAt: Timestamp!
  notes: String
  priority: String
}

type Notification @table {
  user: User!
  task: Task
  contract: Contract
  stakeholder: Stakeholder
  message: String!
  type: String!
  isRead: Boolean!
  createdAt: Timestamp!
  linkTo: String
}